// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";


export type IdentityConnected = {
	};

// A namespace for generated helper functions.
export namespace IdentityConnected {
	// A function which returns this type represented as an AlgebraicType.
	// This function is derived from the AlgebraicType used to generate this type.
	export function getAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
		]);
	}

	export function serialize(writer: BinaryWriter, value: IdentityConnected): void {
	    IdentityConnected.getAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): IdentityConnected {
	    return IdentityConnected.getAlgebraicType().deserialize(reader);
	}
}

// Implements the serialization of the reducer arguments `__identity_connected__`.
export default (connection: DBConnection, args: IdentityConnected) => {
    const writer = new BinaryWriter(1024);
    IdentityConnected.serialize(writer, args);
    const argsBuffer = writer.getBuffer();
    connection.callReducer("__identity_connected__", argsBuffer);
}

