// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";



const REMOTE_MODULE = {
	tables: {
		User: {
			tableName: "User",
			rowType: User.getAlgebraicType(),
			primaryKey: "identity",
		},
		Message: {
			tableName: "Message",
			rowType: Message.getAlgebraicType(),
		},
		},
		reducers: {
			__identity_connected__: {
				reducerName: "__identity_connected__",
				argsType: IdentityConnected.getAlgebraicType(),
			},
			set_name: {
				reducerName: "set_name",
				argsType: SetName.getAlgebraicType(),
			},
			send_message: {
				reducerName: "send_message",
				argsType: SendMessage.getAlgebraicType(),
			},
			__identity_disconnected__: {
				reducerName: "__identity_disconnected__",
				argsType: IdentityDisconnected.getAlgebraicType(),
			},
			__init__: {
				reducerName: "__init__",
				argsType: Init.getAlgebraicType(),
			},
		},
	}
