// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";


export type Init = {
	};

// A namespace for generated helper functions.
export namespace Init {
	// A function which returns this type represented as an AlgebraicType.
	// This function is derived from the AlgebraicType used to generate this type.
	export function getAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
		]);
	}

	export function fromAlgebraicValue(value: AlgebraicValue): Init {
		let productValue = value.asProductValue();
		return {
		};
	}

	export function serialize(writer: BinaryWriter, value: Init): void {
	    Init.getAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): Init {
	    return Init.getAlgebraicType().deserialize(reader);
	}
}

// Implements the serialization of the reducer arguments `__init__`.
export default (connection: DBConnection, args: Init) => {
    const writer = new BinaryWriter(1024);
    Init.serialize(writer, args);
    const argsBuffer = writer.getBuffer();
    connection.callReducer("__init__", argsBuffer);
}

