// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";

export type Message = {
	sender: Identity,
	sent: BigInt,
	text: string,
};

// A namespace for generated helper functions.
export namespace Message {
	// A function which returns this type represented as an AlgebraicType.
	// This function is derived from the AlgebraicType used to generate this type.
	export function getAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
			new ProductTypeElement("sender", Identity.getAlgebraicType()),
			new ProductTypeElement("sent", AlgebraicType.createU64Type()),
			new ProductTypeElement("text", AlgebraicType.createStringType()),
		]);
	}

	export function fromAlgebraicValue(value: AlgebraicValue): Message {
		let productValue = value.asProductValue();
		return {
			sender: productValue.elements[0].asIdentity(),
			sent: productValue.elements[1].asBigInt(),
			text: productValue.elements[2].asString(),
		};
	}

	export function serialize(writer: BinaryWriter, value: Message): void {
	    Message.getAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): Message {
	    return Message.getAlgebraicType().deserialize(reader);
	}
}


