// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";

export type Message = {
	sender: Identity,
	sent: BigInt,
	text: string,
};

// A namespace for generated helper functions.
export namespace Message {
	// A function which returns this type represented as an AlgebraicType.
	// This function is derived from the AlgebraicType used to generate this type.
	export function getAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
			new ProductTypeElement("sender", AlgebraicType.createIdentityType()),
			new ProductTypeElement("sent", AlgebraicType.createU64Type()),
			new ProductTypeElement("text", AlgebraicType.createStringType()),
		]);
	}

	export function serialize(writer: BinaryWriter, value: Message): void {
	    Message.getAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): Message {
	    return Message.getAlgebraicType().deserialize(reader);
	}
}


