// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";


export type SetName = {
	name: string,
};

// A namespace for generated helper functions.
export namespace SetName {
	// A function which returns this type represented as an AlgebraicType.
	// This function is derived from the AlgebraicType used to generate this type.
	export function getAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
			new ProductTypeElement("name", AlgebraicType.createStringType()),
		]);
	}

	export function fromAlgebraicValue(value: AlgebraicValue): SetName {
		let productValue = value.asProductValue();
		return {
			name: productValue.elements[0].asString(),
		};
	}

	export function serialize(writer: BinaryWriter, value: SetName): void {
	    SetName.getAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): SetName {
	    return SetName.getAlgebraicType().deserialize(reader);
	}
}

// Implements the serialization of the reducer arguments `set_name`.
export default (connection: DBConnection, args: SetName) => {
    const writer = new BinaryWriter(1024);
    SetName.serialize(writer, args);
    const argsBuffer = writer.getBuffer();
    connection.callReducer("set_name", argsBuffer);
}

