// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
    AlgebraicType,
    ProductType,
    ProductTypeElement,
    SumType,
    SumTypeVariant,
    AlgebraicValue,
    Identity,
    Address,
    DBConnection,
    TableCache,
    BinaryWriter,
    BinaryReader,
} from "@clockworklabs/spacetimedb-sdk";

export type User = {
	identity: Identity,
	name: string | undefined,
	online: boolean,
};

// A namespace for generated helper functions.
export namespace User {
	// A function which returns this type represented as an AlgebraicType.
	// This function is derived from the AlgebraicType used to generate this type.
	export function getAlgebraicType(): AlgebraicType {
		return AlgebraicType.createProductType([
			new ProductTypeElement("identity", Identity.getAlgebraicType()),
			new ProductTypeElement("name", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
			new ProductTypeElement("online", AlgebraicType.createBoolType()),
		]);
	}

	export function serialize(writer: BinaryWriter, value: User): void {
	    User.getAlgebraicType().serialize(writer, value);
	}

	export function deserialize(reader: BinaryReader): User {
	    return User.getAlgebraicType().deserialize(reader);
	}
}


