// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { AlgebraicType, AlgebraicValue, ProductTypeElement } from "../index";
// @ts-ignore
import { TableUpdate } from "./table_update";

export class DatabaseUpdate {
  static tableName = "DatabaseUpdate";
  tables: TableUpdate[];

  static primaryKey: string | undefined = undefined;

  constructor(tables: TableUpdate[]) {
    this.tables = tables;
  }

  static serialize(value: DatabaseUpdate): object {
    return [value.tables.map((el) => TableUpdate.serialize(el))];
  }

  static getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        "tables",
        AlgebraicType.createArrayType(TableUpdate.getAlgebraicType())
      ),
    ]);
  }

  static fromValue(value: AlgebraicValue): DatabaseUpdate {
    let productValue = value.asProductValue();
    let __tables = productValue.elements[0]
      .asArray()
      .map((el) => TableUpdate.fromValue(el)) as TableUpdate[];
    return new this(__tables);
  }
}

export default DatabaseUpdate;
