// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
} from '../index';
export type EnergyQuanta = {
  quanta: bigint;
};

/**
 * A namespace for generated helper functions.
 */
export namespace EnergyQuanta {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('quanta', AlgebraicType.createU128Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EnergyQuanta): void {
    const converted = {
      quanta: value.quanta,
    };
    EnergyQuanta.getAlgebraicType().serialize(writer, converted);
  }

  export function deserialize(reader: BinaryReader): EnergyQuanta {
    const value = EnergyQuanta.getAlgebraicType().deserialize(reader);
    return {
      quanta: value.quanta,
    };
  }
}
