// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContext,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
} from '../index';
// @ts-ignore
import { DatabaseUpdate as __DatabaseUpdate } from './database_update_type';

export type InitialSubscription = {
  databaseUpdate: __DatabaseUpdate;
  requestId: number;
  totalHostExecutionDurationMicros: bigint;
};

/**
 * A namespace for generated helper functions.
 */
export namespace InitialSubscription {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'database_update',
        __DatabaseUpdate.getAlgebraicType()
      ),
      new ProductTypeElement('request_id', AlgebraicType.createU32Type()),
      new ProductTypeElement(
        'total_host_execution_duration_micros',
        AlgebraicType.createU64Type()
      ),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: InitialSubscription
  ): void {
    const converted = {
      database_update: value.databaseUpdate,
      request_id: value.requestId,
      total_host_execution_duration_micros:
        value.totalHostExecutionDurationMicros,
    };
    InitialSubscription.getAlgebraicType().serialize(writer, converted);
  }

  export function deserialize(reader: BinaryReader): InitialSubscription {
    const value = InitialSubscription.getAlgebraicType().deserialize(reader);
    return {
      databaseUpdate: value.database_update,
      requestId: value.request_id,
      totalHostExecutionDurationMicros:
        value.total_host_execution_duration_micros,
    };
  }
}
