// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
} from '../index';
export type ReducerCallInfo = {
  reducerName: string;
  reducerId: number;
  args: Uint8Array;
  requestId: number;
};

/**
 * A namespace for generated helper functions.
 */
export namespace ReducerCallInfo {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('reducer_name', AlgebraicType.createStringType()),
      new ProductTypeElement('reducer_id', AlgebraicType.createU32Type()),
      new ProductTypeElement(
        'args',
        AlgebraicType.createArrayType(AlgebraicType.createU8Type())
      ),
      new ProductTypeElement('request_id', AlgebraicType.createU32Type()),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: ReducerCallInfo
  ): void {
    const converted = {
      reducer_name: value.reducerName,
      reducer_id: value.reducerId,
      args: value.args,
      request_id: value.requestId,
    };
    ReducerCallInfo.getAlgebraicType().serialize(writer, converted);
  }

  export function deserialize(reader: BinaryReader): ReducerCallInfo {
    const value = ReducerCallInfo.getAlgebraicType().deserialize(reader);
    return {
      reducerName: value.reducer_name,
      reducerId: value.reducer_id,
      args: value.args,
      requestId: value.request_id,
    };
  }
}
