// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContext,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
} from '../index';
export type Subscribe = {
  queryStrings: string[];
  requestId: number;
};

/**
 * A namespace for generated helper functions.
 */
export namespace Subscribe {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'query_strings',
        AlgebraicType.createArrayType(AlgebraicType.createStringType())
      ),
      new ProductTypeElement('request_id', AlgebraicType.createU32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Subscribe): void {
    const converted = {
      query_strings: value.queryStrings,
      request_id: value.requestId,
    };
    Subscribe.getAlgebraicType().serialize(writer, converted);
  }

  export function deserialize(reader: BinaryReader): Subscribe {
    const value = Subscribe.getAlgebraicType().deserialize(reader);
    return {
      queryStrings: value.query_strings,
      requestId: value.request_id,
    };
  }
}
