// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
} from '@clockworklabs/spacetimedb-sdk';
// @ts-ignore
import { Point as __Point } from './point_type';

export type Player = {
  ownerId: string;
  name: string;
  location: __Point;
};

/**
 * A namespace for generated helper functions.
 */
export namespace Player {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('owner_id', AlgebraicType.createStringType()),
      new ProductTypeElement('name', AlgebraicType.createStringType()),
      new ProductTypeElement('location', __Point.getAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Player): void {
    const converted = {
      owner_id: value.ownerId,
      name: value.name,
      location: value.location,
    };
    Player.getAlgebraicType().serialize(writer, converted);
  }

  export function deserialize(reader: BinaryReader): Player {
    const value = Player.getAlgebraicType().deserialize(reader);
    return {
      ownerId: value.owner_id,
      name: value.name,
      location: value.location,
    };
  }
}
