// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
} from "@clockworklabs/spacetimedb-sdk";
export type Point = {
  x: number,
  y: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Point {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("x", AlgebraicType.createU16Type()),
      new ProductTypeElement("y", AlgebraicType.createU16Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Point): void {
    const converted = {
      x: value.x,
      y: value.y,
    };
    Point.getAlgebraicType().serialize(writer, converted);
  }

  export function deserialize(reader: BinaryReader): Point {
    const value = Point.getAlgebraicType().deserialize(reader);
    return {
      x: value.x,
      y: value.y,
    };
  }

}


