// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';
import { UnindexedPlayer } from './unindexed_player_type';
import { Point as __Point } from './point_type';

import { EventContext, Reducer, RemoteReducers, RemoteTables } from '.';

/**
 * Table handle for the table `unindexed_player`.
 *
 * Obtain a handle from the [`unindexedPlayer`] property on [`RemoteTables`],
 * like `ctx.db.unindexedPlayer`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.unindexedPlayer.on_insert(...)`.
 */
export class UnindexedPlayerTableHandle {
  tableCache: TableCache<UnindexedPlayer>;

  constructor(tableCache: TableCache<UnindexedPlayer>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<UnindexedPlayer> {
    return this.tableCache.iter();
  }

  onInsert = (cb: (ctx: EventContext, row: UnindexedPlayer) => void) => {
    return this.tableCache.onInsert(cb);
  };

  removeOnInsert = (cb: (ctx: EventContext, row: UnindexedPlayer) => void) => {
    return this.tableCache.removeOnInsert(cb);
  };

  onDelete = (cb: (ctx: EventContext, row: UnindexedPlayer) => void) => {
    return this.tableCache.onDelete(cb);
  };

  removeOnDelete = (cb: (ctx: EventContext, row: UnindexedPlayer) => void) => {
    return this.tableCache.removeOnDelete(cb);
  };
}
