// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from '@clockworklabs/spacetimedb-sdk';
import { Point as __Point } from './point_type';

export type UnindexedPlayer = {
  ownerId: string;
  name: string;
  location: __Point;
};

/**
 * A namespace for generated helper functions.
 */
export namespace UnindexedPlayer {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('ownerId', AlgebraicType.createStringType()),
      new ProductTypeElement('name', AlgebraicType.createStringType()),
      new ProductTypeElement('location', __Point.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(
    writer: BinaryWriter,
    value: UnindexedPlayer
  ): void {
    UnindexedPlayer.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UnindexedPlayer {
    return UnindexedPlayer.getTypeScriptAlgebraicType().deserialize(reader);
  }
}
